name: "Prepare for Release"
on:
  workflow_dispatch:
    inputs:
       new_version:
         
         description: "Release Version (no 'v')"
         required: true
         type: string

jobs:
  prepare-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update Changelog
        uses: thomaseizinger/keep-a-changelog-new-release@1.3.0
        with:
          tag: v${{ github.event.inputs.new_version }}
          version: ${{ github.event.inputs.new_version }}
      - uses: actions/upload-artifact@v3
        with:
          name: release_notes
          path: CHANGELOG.md
